### PR TITLE
Midi json using cairo

### PR DESCRIPTION
**Pull request by od-hunter**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by od-hunter** [comment]
@caseywescott please review,
Screenshot 2024-11-24 025730
 i am having errors running "scarb build"

**Comment by caseywescott** [comment]
what scarb are you running?

**Comment by od-hunter** [comment]
am running scarb build

**Comment by caseywescott** [comment]
I mean what version are you running? The repo is currently configured to scarb 2.6.3 per .tools-versions file

**Comment by caseywescott** [comment]
it currently runs on 2.6.3 ...There are breaking changes running at v2.8.5.

You can either run on 2.6.3 or wait until i have someone upgrade the repo to v2.8.5. let me know what you want to do

**Comment by od-hunter** [comment]
@caseywescott please any update on the upgrade?

**Comment by caseywescott** [comment]
The dependancies wont be upgraded in time for the hackathon. so it'll have to run on 2.6.3. what error do you get?

**Comment by od-hunter** [comment]
bfd892a3-8ead-41a0-8a9e-22152acbea21
125dd818-5f75-4a34-9871-a2af1c5f1a42

**Comment by od-hunter** [comment]
See the errors please @caseywescott

**Comment by caseywescott** [comment]
I dont think vec is a cairo data type, its a rust convention

**Comment by od-hunter** [comment]
Hi @caseywescott , Please, do u have a propose solution, I have tried on my end, I thought it from my machine. I tried it on another but still getting the same error….I see that the error is not from the new file I created that's why am asking

**Comment by caseywescott** [comment]
Id try using a span or array instead of a vector.

**Pull request merged**
